### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by ronna-s** [wwgberlin/go-event-sourcing-exercise#1]
- [ ] Add a slider
- [x] Add a proper parser to moves
- [x] Make a wrapper for the `chess` package so it doesn't interfere with the implementation.
- [ ] Fix the whole `board.go` file with the image sources - this doesn't belong there.

For the workshop implementation:
- [ ] Add a rollback event, the women will then learn about how to use slices to support this behavior.
- [ ] The move parsing will be up for implementation too?
- [x] Multiple games? - Then create event sourcing for each game separately (talk about actor pattern).

**Comment by dariakameneva** [comment]
Regarding the last point - I've actually started that yesterday, refactoring at the moment. This is quite important because this way we can show how events for different entities (i.e. games) can exist in a single storage and how we are going to filter them.

**Comment by ronna-s** [comment]
I think we can have different events we can dispatch - new game , check mate, check, draw, forfeit, move, move validated, move rejected, promote, promotion validated, promotion rejected, etc, and we can have different consumers - one will be deal with the game, one will manage the scores, one will check if the moves are valid and publish events for moves that are valid, so the consumer handling the game moves will not have to deal with invalid events, etc. 
What do you think?
